import { createTagAnalyzerTimeRange, flattenTagAnalyzerPanelInfo, normalizeTagAnalyzerPanelInfo } from './PanelModelUtils';

describe('PanelModelUtils', () => {
    describe('createTagAnalyzerTimeRange', () => {
        it('returns a simple time range object', () => {
            expect(createTagAnalyzerTimeRange(100, 200)).toEqual({
                startTime: 100,
                endTime: 200,
            });
        });
    });

    describe('normalizeTagAnalyzerPanelInfo', () => {
        it('returns nested panel info unchanged when it is already normalized', () => {
            const nestedPanelInfo = {
                meta: {
                    index_key: 'panel-1',
                    chart_title: 'Panel 1',
                },
                data: {
                    tag_set: [],
                    raw_keeper: false,
                    count: 0,
                    interval_type: '',
                },
                time: {
                    range_bgn: 0,
                    range_end: 100,
                    use_time_keeper: false,
                    time_keeper: '',
                    default_range: { min: 0, max: 100 },
                },
                axes: {
                    show_x_tickline: false,
                    pixels_per_tick_raw: 1,
                    pixels_per_tick: 1,
                    use_sampling: false,
                    sampling_value: 0,
                    zero_base: false,
                    show_y_tickline: false,
                    custom_min: 0,
                    custom_max: 0,
                    custom_drilldown_min: 0,
                    custom_drilldown_max: 0,
                    use_ucl: false,
                    ucl_value: 0,
                    use_lcl: false,
                    lcl_value: 0,
                    use_right_y2: false,
                    zero_base2: false,
                    show_y_tickline2: false,
                    custom_min2: 0,
                    custom_max2: 0,
                    custom_drilldown_min2: 0,
                    custom_drilldown_max2: 0,
                    use_ucl2: false,
                    ucl2_value: 0,
                    use_lcl2: false,
                    lcl2_value: 0,
                },
                display: {
                    show_legend: false,
                    use_zoom: false,
                    chart_type: 'Line',
                    show_point: false,
                    point_radius: 0,
                    fill: 0,
                    stroke: 0,
                },
                use_normalize: 'Y',
            } as any;

            expect(normalizeTagAnalyzerPanelInfo(nestedPanelInfo)).toBe(nestedPanelInfo);
        });

        it('normalizes flat panel info into the nested shape', () => {
            const flatPanelInfo = {
                index_key: 'panel-1',
                chart_title: 'Panel 1',
                tag_set: [],
                range_bgn: 0,
                range_end: 100,
                raw_keeper: false,
                time_keeper: '',
                default_range: { min: 0, max: 100 },
                count: 0,
                interval_type: '',
                show_legend: false,
                use_zoom: false,
                use_time_keeper: false,
                show_x_tickline: false,
                pixels_per_tick_raw: '12',
                pixels_per_tick: '24',
                use_sampling: false,
                sampling_value: '0',
                zero_base: false,
                show_y_tickline: false,
                custom_min: '',
                custom_max: '',
                custom_drilldown_min: '',
                custom_drilldown_max: '',
                use_ucl: false,
                ucl_value: '',
                use_lcl: false,
                lcl_value: '',
                use_right_y2: false,
                zero_base2: false,
                show_y_tickline2: false,
                custom_min2: '',
                custom_max2: '',
                custom_drilldown_min2: '',
                custom_drilldown_max2: '',
                use_ucl2: false,
                ucl2_value: '',
                use_lcl2: false,
                lcl2_value: '',
                chart_type: 'Line',
                show_point: false,
                point_radius: '3',
                fill: '0',
                stroke: '0',
                use_normalize: 'N',
            } as any;

            expect(normalizeTagAnalyzerPanelInfo(flatPanelInfo)).toEqual({
                meta: {
                    index_key: 'panel-1',
                    chart_title: 'Panel 1',
                },
                data: {
                    tag_set: [],
                    raw_keeper: false,
                    count: 0,
                    interval_type: '',
                },
                time: {
                    range_bgn: 0,
                    range_end: 100,
                    use_time_keeper: false,
                    time_keeper: '',
                    default_range: { min: 0, max: 100 },
                },
                axes: {
                    show_x_tickline: false,
                    pixels_per_tick_raw: 12,
                    pixels_per_tick: 24,
                    use_sampling: false,
                    sampling_value: 0,
                    zero_base: false,
                    show_y_tickline: false,
                    custom_min: 0,
                    custom_max: 0,
                    custom_drilldown_min: 0,
                    custom_drilldown_max: 0,
                    use_ucl: false,
                    ucl_value: 0,
                    use_lcl: false,
                    lcl_value: 0,
                    use_right_y2: false,
                    zero_base2: false,
                    show_y_tickline2: false,
                    custom_min2: 0,
                    custom_max2: 0,
                    custom_drilldown_min2: 0,
                    custom_drilldown_max2: 0,
                    use_ucl2: false,
                    ucl2_value: 0,
                    use_lcl2: false,
                    lcl2_value: 0,
                },
                display: {
                    show_legend: false,
                    use_zoom: false,
                    chart_type: 'Line',
                    show_point: false,
                    point_radius: 3,
                    fill: 0,
                    stroke: 0,
                },
                use_normalize: 'N',
            });
        });
    });

    describe('flattenTagAnalyzerPanelInfo', () => {
        it('flattens nested panel info back to the legacy shape', () => {
            const nestedPanelInfo = {
                meta: {
                    index_key: 'panel-1',
                    chart_title: 'Panel 1',
                },
                data: {
                    tag_set: [],
                    raw_keeper: false,
                    count: 0,
                    interval_type: '',
                },
                time: {
                    range_bgn: 0,
                    range_end: 100,
                    use_time_keeper: false,
                    time_keeper: '',
                    default_range: { min: 0, max: 100 },
                },
                axes: {
                    show_x_tickline: false,
                    pixels_per_tick_raw: 12,
                    pixels_per_tick: 24,
                    use_sampling: false,
                    sampling_value: 0,
                    zero_base: false,
                    show_y_tickline: false,
                    custom_min: 0,
                    custom_max: 0,
                    custom_drilldown_min: 0,
                    custom_drilldown_max: 0,
                    use_ucl: false,
                    ucl_value: 0,
                    use_lcl: false,
                    lcl_value: 0,
                    use_right_y2: false,
                    zero_base2: false,
                    show_y_tickline2: false,
                    custom_min2: 0,
                    custom_max2: 0,
                    custom_drilldown_min2: 0,
                    custom_drilldown_max2: 0,
                    use_ucl2: false,
                    ucl2_value: 0,
                    use_lcl2: false,
                    lcl2_value: 0,
                },
                display: {
                    show_legend: false,
                    use_zoom: false,
                    chart_type: 'Line',
                    show_point: false,
                    point_radius: 3,
                    fill: 0,
                    stroke: 0,
                },
                use_normalize: 'Y',
            } as any;

            expect(flattenTagAnalyzerPanelInfo(nestedPanelInfo)).toEqual({
                index_key: 'panel-1',
                chart_title: 'Panel 1',
                tag_set: [],
                range_bgn: 0,
                range_end: 100,
                raw_keeper: false,
                time_keeper: '',
                default_range: { min: 0, max: 100 },
                count: 0,
                interval_type: '',
                show_legend: false,
                use_zoom: false,
                use_time_keeper: false,
                show_x_tickline: false,
                pixels_per_tick_raw: 12,
                pixels_per_tick: 24,
                use_sampling: false,
                sampling_value: 0,
                zero_base: false,
                show_y_tickline: false,
                custom_min: 0,
                custom_max: 0,
                custom_drilldown_min: 0,
                custom_drilldown_max: 0,
                use_ucl: false,
                ucl_value: 0,
                use_lcl: false,
                lcl_value: 0,
                use_right_y2: false,
                zero_base2: false,
                show_y_tickline2: false,
                custom_min2: 0,
                custom_max2: 0,
                custom_drilldown_min2: 0,
                custom_drilldown_max2: 0,
                use_ucl2: false,
                ucl2_value: 0,
                use_lcl2: false,
                lcl2_value: 0,
                chart_type: 'Line',
                show_point: false,
                point_radius: 3,
                fill: 0,
                stroke: 0,
                use_normalize: 'Y',
            });
        });
    });
});
