import type { LegacyCompatibleSeriesConfig, LegacyTimeValue } from '../../legacy/LegacyTypes';
import type { PanelEChartType } from '../../panelModelTypes';
import type { ValueRange } from '../../../TagAnalyzerCommonTypes';
import type { TimeRangeConfig, TimeRangePair } from '../../time/types/TimeTypes';

export type LegacyFlatPanelInfo = {
    index_key: string;
    chart_title: string;
    tag_set: LegacyCompatibleSeriesConfig[];
    range_bgn: LegacyTimeValue;
    range_end: LegacyTimeValue;
    raw_keeper: boolean | undefined;
    time_keeper: Partial<TimeRangePair> | '' | undefined;
    default_range: ValueRange | undefined;
    count: number | undefined;
    interval_type: string | undefined;
    show_legend: 'Y' | 'N';
    use_zoom: 'Y' | 'N';
    use_normalize: 'Y' | 'N' | undefined;
    use_time_keeper: 'Y' | 'N';
    show_x_tickline: 'Y' | 'N';
    pixels_per_tick_raw: number | string;
    pixels_per_tick: number | string;
    use_sampling: boolean;
    sampling_value: number | string;
    zero_base: 'Y' | 'N';
    show_y_tickline: 'Y' | 'N';
    custom_min: number | string;
    custom_max: number | string;
    custom_drilldown_min: number | string;
    custom_drilldown_max: number | string;
    use_ucl: 'Y' | 'N';
    ucl_value: number | string;
    use_lcl: 'Y' | 'N';
    lcl_value: number | string;
    use_right_y2: 'Y' | 'N';
    zero_base2: 'Y' | 'N';
    show_y_tickline2: 'Y' | 'N';
    custom_min2: number | string;
    custom_max2: number | string;
    custom_drilldown_min2: number | string;
    custom_drilldown_max2: number | string;
    use_ucl2: 'Y' | 'N';
    ucl2_value: number | string;
    use_lcl2: 'Y' | 'N';
    lcl2_value: number | string;
    chart_type: PanelEChartType;
    show_point: 'Y' | 'N';
    point_radius: number | string;
    fill: number | string;
    stroke: number | string;
    range_config?: TimeRangeConfig | undefined;
    [key: string]: unknown;
};
