name: auto Build

on:
    pull_request:
        branches: [main, dev_*]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - run: npm install
            - run: npm run test

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
            - run: npm run build
            - run: npm run test
