name: auto Build

on:
    pull_request:
        branches: [main, dev_v2]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - run: npm install
            - run: npm run build
