name: build ci

on:
  push:
    branches:
      - 'main'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
            node-version: 16.x

      - name: Checkout
        uses: actions/checkout@master

      - run: npm install
      - run: npm run build --if-present
      - uses: vimtor/action-zip@v1
        with:
            files: dist/ui/
            recursive: true
            dest: web-ui.zip

      - name: Release files
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.GIT_PASS }}
          file: web-ui.zip
          repo_name: machbase/neo-web
          prerelease: true
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
