name: Upload build file into Artifact

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - run: npm install
            - run: npm run build

            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: NeoWeb
                  path: ./dist
